### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cjeanneret** [EthACKdotOrg/orWall#43]
Bullet-points for roadmap. Better than static file in git.
May link to already-existing issues in here. It's just a centralized brain dump.
- [x] Add SSH support like ADB (#44)
- [ ] Debugging: add log feature (see [Network Log](https://code.google.com/p/iptableslog/source/browse/src/com/googlecode/networklog/Iptables.java) and /proc/kmsg) (#42)
  - [ ] Find a way to get nflog output for sucky kernels…
    - probably using some [WinPcap implementation](http://jnetpcap.com/)
- [x] Allow app to bypass all the firewall stuff
- [ ] add i2p support once there is some reliable client lib (#12)
- [ ] better orbot integration using NetCipher and API calls once it's implemented (#11)
- [x] Allow to disable (and re-enable) orWall
- [ ] Create widgets (#36)
- [ ] Get more translations
- [ ] Get more people involved ;)
- [ ] Take over the World in the Name of Privacy
- [ ] Support rules per connection (Wifi, Data, Roaming) (requested two times)
